name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código
      - name: Checkout
        uses: actions/checkout@v3

      # Gera a cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: RoniJrr
          outputs: dist/github-contribution-grid-snake.svg

      # Publica no branch output
      - name: Push Snake Animation to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output

